export const AUTH_UPDATE = 'AUTH_UPDATE'

export const UI_OPEN_SIDEBAR = 'UI_OPEN_SIDEBAR'
export const UI_CLOSE_SIDEBAR = 'UI_CLOSE_SIDEBAR'
export const UI_SET_HEADER_TITLE_OVERRIDE = 'UI_SET_HEADER_TITLE_OVERRIDE'
export const UI_CLEAR_HEADER_TITLE_OVERRIDE = 'UI_CLEAR_HEADER_TITLE_OVERRIDE'

export const FOLDERS_INSERT = 'FOLDERS_INSERT'
export const FOLDERS_CLEAR = 'FOLDERS_CLEAR'
export const FOLDER_INSERT = 'FOLDER_INSERT'
export const FOLDER_UPDATE = 'FOLDER_UPDATE'
export const FOLDER_DELETE = 'FOLDER_DELETE'
export const FOLDER_START_LOADING = 'FOLDER_START_LOADING'
export const FOLDER_STOP_LOADING = 'FOLDER_STOP_LOADING'

export const DEVIAIONS_INSERT = 'DEVIAIONS_INSERT'
export const DEVIAIONS_CLEAR = 'DEVIAIONS_CLEAR'
export const DEVIAION_INSERT = 'DEVIAION_INSERT'
export const DEVIATION_UPDATE = 'DEVIATION_UPDATE'

export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA'
export const SYNC_STORAGE = 'SYNC_STORAGE'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
